/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateEmployeeRouteImport } from './routes/create-employee'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditEmployeeIdRouteImport } from './routes/edit-employee/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateEmployeeRoute = CreateEmployeeRouteImport.update({
  id: '/create-employee',
  path: '/create-employee',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditEmployeeIdRoute = EditEmployeeIdRouteImport.update({
  id: '/edit-employee/$id',
  path: '/edit-employee/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-employee': typeof CreateEmployeeRoute
  '/login': typeof LoginRoute
  '/edit-employee/$id': typeof EditEmployeeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-employee': typeof CreateEmployeeRoute
  '/login': typeof LoginRoute
  '/edit-employee/$id': typeof EditEmployeeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-employee': typeof CreateEmployeeRoute
  '/login': typeof LoginRoute
  '/edit-employee/$id': typeof EditEmployeeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-employee' | '/login' | '/edit-employee/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-employee' | '/login' | '/edit-employee/$id'
  id: '__root__' | '/' | '/create-employee' | '/login' | '/edit-employee/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateEmployeeRoute: typeof CreateEmployeeRoute
  LoginRoute: typeof LoginRoute
  EditEmployeeIdRoute: typeof EditEmployeeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-employee': {
      id: '/create-employee'
      path: '/create-employee'
      fullPath: '/create-employee'
      preLoaderRoute: typeof CreateEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-employee/$id': {
      id: '/edit-employee/$id'
      path: '/edit-employee/$id'
      fullPath: '/edit-employee/$id'
      preLoaderRoute: typeof EditEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateEmployeeRoute: CreateEmployeeRoute,
  LoginRoute: LoginRoute,
  EditEmployeeIdRoute: EditEmployeeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
